# Pandas

In [1]:
# Import module
import pandas as pd

In [2]:
# Read csv 
df = pd.read_csv("https://vincentarelbundock.github.io/Rdatasets/csv/boot/urine.csv")
# Pandas can also read other data formats
# pd.read_excel('file.xlsx',sheet_name='Sheet1', index_col=None, na_values=['NA'])

In [4]:
# List first 5 rows
df.head(5)

rownames  r  gravity    ph   osmo  cond  urea  calc
0         1  0    1.021  4.91  725.0   NaN   443  2.45
1         2  0    1.017  5.74  577.0  20.0   296  4.49
2         3  0    1.008  7.20  321.0  14.9   101  2.36
3         4  0    1.011  5.51  408.0  12.6   224  2.15
4         5  0    1.005  6.52  187.0   7.5    91  1.16

In [5]:
print("Dimensions of data frame: {}".format(df.shape))
print("Column names: {}".format(df.columns))

Dimensions of data frame: (79, 8)
Column names: Index(['rownames', 'r', 'gravity', 'ph', 'osmo', 'cond', 'urea', 'calc'], dtype='object')


In [6]:
# Check data type of particular column
print("Data type of r column: {}".format(df['r'].dtype))
print("Data type of gravity column: {}".format(df['gravity'].dtype))

Data type of r column: int64
Data type of gravity column: float64


In [7]:
# Data type of all columns
print("Data type of all columns:\n{}".format(df.dtypes))

Data type of all columns:
rownames      int64
r             int64
gravity     float64
ph          float64
osmo        float64
cond        float64
urea          int64
calc        float64
dtype: object


In [7]:
# Basic statistics
print("\nMIN: ", df.min())
print("\nMAX: ", df[['calc']].max())
print("\nMEAN: ", df[['calc']].mean())
print("\nMEDIAN: ", df[['osmo']].median())
print("\nSTD: ", df[['osmo']].std())
# Descriptive stats for numeric columns
print("\nDESCRIBE: ", df[['ph']].describe())


MIN:  rownames      1.000
r             0.000
gravity       1.005
ph            4.760
osmo        187.000
cond          5.100
urea         10.000
calc          0.170
dtype: float64

MAX:  calc    14.34
dtype: float64

MEAN:  calc    4.138987
dtype: float64

MEDIAN:  osmo    612.5
dtype: float64

STD:  osmo    238.247685
dtype: float64

DESCRIBE:                ph
count  79.000000
mean    6.028481
std     0.724307
min     4.760000
25%     5.530000
50%     5.940000
75%     6.385000
max     7.940000


In [8]:
# Drop rows with missing values
df_no_na = df.dropna()
print(df_no_na.head(5))

   rownames  r  gravity    ph   osmo  cond  urea  calc
1         2  0    1.017  5.74  577.0  20.0   296  4.49
2         3  0    1.008  7.20  321.0  14.9   101  2.36
3         4  0    1.011  5.51  408.0  12.6   224  2.15
4         5  0    1.005  6.52  187.0   7.5    91  1.16
5         6  0    1.020  5.27  668.0  25.3   252  3.34


In [9]:
# Group data using r
df_r = df.groupby(['r'])
# Calculate mean calc for groups
print("Means for r groups: {}".format(df_r.mean()))

Means for r groups:    rownames   gravity        ph        osmo       cond        urea      calc
r                                                                           
0      23.0  1.015489  6.098667  565.288889  20.550000  237.111111  2.624889
1      62.5  1.021588  5.935588  682.878788  21.355882  305.176471  6.142941


In [10]:
# Filter/subset data
df_sub = df[ df['calc']>9 ]
print("\nSubset calc>9:\n", df_sub)
print("\nSubset calc column only:\n", df_sub['calc'])


Subset calc>9:
     rownames  r  gravity    ph    osmo  cond  urea   calc
46        47  1    1.024  5.77   698.0  19.5   354  13.00
50        51  1    1.026  5.16   822.0  26.0   301  14.34
62        63  1    1.034  5.24  1236.0  27.3   620  12.68
74        75  1    1.025  7.90   721.0  23.6   301   9.04
77        78  1    1.016  6.81   594.0  21.4   255  12.20
78        79  1    1.015  6.03   416.0  12.8   178   9.39

Subset calc column only:
 46    13.00
50    14.34
62    12.68
74     9.04
77    12.20
78     9.39
Name: calc, dtype: float64


In [11]:
# Select rows where r=1
df_r1 = df[ df['r']==1 ]
print("\nRows where r=1:\n", df_r1)
# Select and filter
df_r1_calc4 = df[ (df['r']==1) & (df['calc']<4) ]
print("\nRows where r=1 and calc<4:\n", df_r1_calc4)


Rows where r=1:
     rownames  r  gravity    ph    osmo  cond  urea   calc
45        46  1    1.021  5.94   774.0  27.9   325   6.96
46        47  1    1.024  5.77   698.0  19.5   354  13.00
47        48  1    1.024  5.60   866.0  29.5   360   5.54
48        49  1    1.021  5.53   775.0  31.2   302   6.19
49        50  1    1.024  5.36   853.0  27.6   364   7.31
50        51  1    1.026  5.16   822.0  26.0   301  14.34
51        52  1    1.013  5.86   531.0  21.4   197   4.74
52        53  1    1.010  6.27   371.0  11.2   188   2.50
53        54  1    1.011  7.01   443.0  21.4   124   1.27
54        55  1    1.022  6.21     NaN  20.6   398   4.18
55        56  1    1.011  6.13   364.0  10.9   159   3.10
56        57  1    1.031  5.73   874.0  17.4   516   3.01
57        58  1    1.020  7.94   567.0  19.7   212   6.81
58        59  1    1.040  6.28   838.0  14.3   486   8.28
59        60  1    1.021  5.56   658.0  23.6   224   2.33
60        61  1    1.025  5.71   854.0  27.0   385   7

In [12]:
# Selecting/slicing rows (first row position 0!)
print("Rows 41-50: ", df[40:50])

Rows 41-50:      rownames  r  gravity    ph   osmo  cond  urea   calc
40        41  0    1.021  5.33  815.0  26.0   385   2.66
41        42  0    1.009  5.64  386.0  17.7   104   1.22
42        43  0    1.015  6.79  541.0  20.9   187   2.64
43        44  0    1.010  5.97  343.0  13.4   126   2.31
44        45  0    1.020  5.68  876.0  35.8   308   4.49
45        46  1    1.021  5.94  774.0  27.9   325   6.96
46        47  1    1.024  5.77  698.0  19.5   354  13.00
47        48  1    1.024  5.60  866.0  29.5   360   5.54
48        49  1    1.021  5.53  775.0  31.2   302   6.19
49        50  1    1.024  5.36  853.0  27.6   364   7.31


In [13]:
# Select rows and columns with loc method
df_loc = df.loc[40:50,['r','calc']]
print(df_loc)

    r   calc
40  0   2.66
41  0   1.22
42  0   2.64
43  0   2.31
44  0   4.49
45  1   6.96
46  1  13.00
47  1   5.54
48  1   6.19
49  1   7.31
50  1  14.34


In [14]:
# Select rows and columns using positions with iloc method
df_iloc = df.iloc[40:50,[1,3,7]]
print("\nMethod iloc:\n", df_iloc)
# One column by position in df_r1_calc4 subset
print("\nColumn selection by position\n", df_r1_calc4[df_r1_calc4.columns[3]])
print("\nColumn selection 2 by position\n", df_r1_calc4.iloc[:,3])
# Another example with iloc method
df_iloc2 = df.iloc[[0,44,45,78], [1,3]]
print("\nAnother example of iloc:\n", df_iloc2)


Method iloc:
     r    ph   calc
40  0  5.33   2.66
41  0  5.64   1.22
42  0  6.79   2.64
43  0  5.97   2.31
44  0  5.68   4.49
45  1  5.94   6.96
46  1  5.77  13.00
47  1  5.60   5.54
48  1  5.53   6.19
49  1  5.36   7.31

Column selection by position
 52    6.27
53    7.01
55    6.13
56    5.73
59    5.56
64    5.98
65    5.58
67    6.75
70    4.76
75    4.81
Name: ph, dtype: float64

Column selection 2 by position
 52    6.27
53    7.01
55    6.13
56    5.73
59    5.56
64    5.98
65    5.58
67    6.75
70    4.76
75    4.81
Name: ph, dtype: float64

Another example of iloc:
     r    ph
0   0  4.91
44  0  5.68
45  1  5.94
78  1  6.03


In [15]:
# Sorted by column calc
df_sorted = df.sort_values( by='calc', ascending=False)
# df_sorted
# shift+tab for doc
# Last rows with tail()
df_sorted.tail()

rownames  r  gravity    ph   osmo  cond  urea  calc
25        26  0    1.017  6.76  455.0   8.8   270  0.77
67        68  1    1.012  6.75  251.0   5.1   141  0.65
75        76  1    1.017  4.81  410.0  13.3   195  0.58
70        71  1    1.028  4.76  312.0  12.4    10  0.27
27        28  0    1.010  6.61  225.0   9.8    72  0.17

# NumPY

### NDARRAY OBJECT

In [16]:
# Import module
import numpy as np

# Create numpy array
a = np.array([1,2,3]) 
print("\n1D array:\n",a)

# With more than one dimension 
b = np.array([[1, 2], [3, 4]]) 
print("\n2D array:\n",b)

# Set minimum dimensions
c = np.array([1,2,3], ndmin = 2) 
print("\nMin.dim.:\n",c)


1D array:
 [1 2 3]

2D array:
 [[1 2]
 [3 4]]

Min.dim.:
 [[1 2 3]]


### NDARRAY SCALAR DATA TYPES (dtype)

Different scalar data types defined in NumPy.

NumPy numerical types are instances of dtype (data-type) object.

The dtype object describes interpretation of fixed block of memory.

In [17]:
# np.int8: -128 to 127
x = np.int8([1,2,4])
print("x (int8): {} --> type: {}".format(x,type(x)))

# np.float32
y = np.float32(1.0)
print("y (float32): ", y)

# np_uint8 (unsigned long)
z = np.arange(3, dtype=np.uint8)
print("z (uint8): ", z)

# Convert type using astype() method
zf = z.astype(float) 
print("uint8 to float: ", zf)

# To know/show dtype
print("Type of z = {}\nType of zf = {}".format(z.dtype,zf.dtype))

x (int8): [1 2 4] --> type: <class 'numpy.ndarray'>
y (float32):  1.0
z (uint8):  [0 1 2]
uint8 to float:  [0. 1. 2.]
Type of z = uint8
Type of zf = float64


In [18]:
# EXAMPLE 1: population data
dt = np.dtype([('country', 'U20'), 
               ('density', 'i4'), 
               ('area', 'i4'), 
               ('population', 'i4')])
# To use 32-bit signed integer: np.dtype('i4')
# To use 64-bit floating-point number: np.dtype('f8')
# To use actual strings in Python 3 use U or np.unicode
# e.g. 25-character string: np.dtype('U20')

# Create nparray with population data
np_population = np.array([
    ('Netherlands', 393, 41526, 16928800),
    ('Belgium', 337, 30510, 11007020),
    ('United Kingdom', 256, 243610, 62262000),
    ('Germany', 233, 357021, 81799600),
    ('Liechtenstein', 205, 160, 32842),
    ('Italy', 192, 301230, 59715625),
    ('Switzerland', 177, 41290, 7301994),
    ('Luxembourg', 173, 2586, 512000),
    ('France', 111, 547030, 63601002),
    ('Austria', 97, 83858, 8169929),
    ('Greece', 81, 131940, 11606813),
    ('Ireland', 65, 70280, 4581269),
    ('Sweden', 20, 449964, 9515744),
    ('Finland', 16, 338424, 5410233),
    ('Norway', 13, 385252, 5033675)],
    dtype=dt)

In [19]:
# Show first 4 elements
print(np_population[:4])

# Iterate over ndarray with for loop
for element in np_population:
    print("\nCountry: {} has population of {}".format(element[0],element[3]))

[('Netherlands', 393,  41526, 16928800) ('Belgium', 337,  30510, 11007020)
 ('United Kingdom', 256, 243610, 62262000)
 ('Germany', 233, 357021, 81799600)]

Country: Netherlands has population of 16928800

Country: Belgium has population of 11007020

Country: United Kingdom has population of 62262000

Country: Germany has population of 81799600

Country: Liechtenstein has population of 32842

Country: Italy has population of 59715625

Country: Switzerland has population of 7301994

Country: Luxembourg has population of 512000

Country: France has population of 63601002

Country: Austria has population of 8169929

Country: Greece has population of 11606813

Country: Ireland has population of 4581269

Country: Sweden has population of 9515744

Country: Finland has population of 5410233

Country: Norway has population of 5033675


### NDARRAY ATTRIBUTES

Array attributes reflect information about the array itself.

Using its attributes you can get (and sometimes set) properties of array without creating a new array.

In [20]:
# dtype
print("DTYPE:\n", np_population.dtype)

# Information about the memory layout of the array 
print("FLAGS:\n", np_population.flags)

DTYPE:
 [('country', '<U20'), ('density', '<i4'), ('area', '<i4'), ('population', '<i4')]
FLAGS:
   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [21]:
# Number of array dimension
print("NDIM:\n", np_population.ndim)

# Tuple of array dimensions
print("SHAPE:\n", np_population.shape)

# Number of elements in array
print("SIZE:\n", np_population.size)

# Length of one array element in bytes
print("ITEMSIZE:\n", np_population.itemsize)

# Total bytes consumed by the elements of the array
print("NBYTES:\n", np_population.nbytes)

NDIM:
 1
SHAPE:
 (15,)
SIZE:
 15
ITEMSIZE:
 92
NBYTES:
 1380


### NDARRAY METHODS

In [22]:
# Copy element of array to standard Python scalar and return it
population_element = np_population[1]
print("Second element from population ndarray:\n", population_element)
    
# Return array as a (possibly nested) list
population_list = np_population.tolist()
print("List:\n", population_list)

# Insert scalar into array, last argument is item
np_population.itemset(1, ('BELGIUM', 337, 30510, 11007020) )
print("ndarray.itemset:\n", np_population[1])

Second element from population ndarray:
 ('Belgium', 337, 30510, 11007020)
List:
 [('Netherlands', 393, 41526, 16928800), ('Belgium', 337, 30510, 11007020), ('United Kingdom', 256, 243610, 62262000), ('Germany', 233, 357021, 81799600), ('Liechtenstein', 205, 160, 32842), ('Italy', 192, 301230, 59715625), ('Switzerland', 177, 41290, 7301994), ('Luxembourg', 173, 2586, 512000), ('France', 111, 547030, 63601002), ('Austria', 97, 83858, 8169929), ('Greece', 81, 131940, 11606813), ('Ireland', 65, 70280, 4581269), ('Sweden', 20, 449964, 9515744), ('Finland', 16, 338424, 5410233), ('Norway', 13, 385252, 5033675)]
ndarray.itemset:
 ('BELGIUM', 337, 30510, 11007020)


### BIOPYTHON

In [23]:
#Import SeqIO from biopython 
from Bio import SeqIO

In [24]:
# Example 2: storing nucleotide frequencies in nparray
def freq_numpy(dna_list):
    frequency_matrix = np.zeros((4, len(dna_list[0])), dtype=np.int32)
    base2index = {'A': 0, 'C': 1, 'G': 2, 'T': 3}
    for dna in dna_list:
        for index, base in enumerate(dna):
            frequency_matrix[base2index[base]][index] += 1
    return frequency_matrix

mm10_dna = "ACACTCAACTGTTTTAGAAG"
print("Frequences of mm10_dna:\n", freq_numpy(mm10_dna))

Frequences of mm10_dna:
 [[7]
 [4]
 [3]
 [6]]


In [25]:
# Import SeqIO from biopython
from Bio import SeqIO
# Fasta file from Leho in jupyter notebook folder
fasta_file = open("mm10_dna.fasta","r")
for seq_record in SeqIO.parse(fasta_file, "fasta"):
    # Get length of fasta record
    print("\nLength of mm10_dna.fasta: ", len(seq_record))
    # Calculate frequencies
    print("\nFrequencies:\n", freq_numpy(seq_record))
fasta_file.close()


Length of mm10_dna.fasta:  31743

Frequencies:
 [[9121]
 [7005]
 [6592]
 [9025]]
